class Solution {
  String longestConsec(strarr, k) {
    if (k <= 0 || strarr.length == 0 || k > strarr.length) return '';
    var longest = '';
    var temp = '';
    List<String> basis = strarr;
    while (basis.length >= k){
      var tempLong = '';
      temp = basis[0];
      for (var i = 0; i < k; i++){
        tempLong += basis[i];
      }
      basis.remove(temp);
      if (tempLong.length > longest.length) longest = tempLong;
    }
    return longest;
  }
}

void main() {
  var sol = Solution();
  print(sol.longestConsec(['zone', 'abigail', 'theta', 'form', 'libe', 'zas'], 2));
  //print(sol.longestConsec(["itvayloxrp","wkppqsztdkmvcuwvereiupccauycnjutlv","vweqilsfytihvrzlaodfixoyxvyuyvgpck"], 1));
  //print(sol.longestConsec(['lxxxguu', 'ncrrri', 'yppplllwwgggrrrrr', 'ttthhbdnxxx', 'ooaaazzgccceeessxqq', 'uffffffuqqyyyi', 'kkhuuub', 'qppssskxx', 'ssjjjifffmmwwffccchhh', 'hhhbbmmm', 'yyyfffnxlllgg', 'cwwffusgggcccvvlw', 'aaahhfff', 'aaaoooavvvfzrrvvvkk', 'ppprrrjjjyyyoooee', 'ooonnncwqqqnlaag', 'zyyyooolllqqq', 'xxgthhhhmmm', 'wsj', 'ekksssdnhdbbvvv', 'fffffuulllmmmbhhh', 'aappzzwwwkkkdbbbboc', 'xddyxoooyyy', 'bbjjjzzkkymxzzz', 'ddiyqqqyyaafffcctw', 'cimmmgggdd', 'nnfffddvvvyqqffj', 'aalllvpppj', 'fgbbblllefffyyydhhhqq', 'xucccsnwwppp', 'cyyybffiosss', 'ssmmmzoooqqqfnmz', 'ooeeeiijj', 'ooowwwgooy', 'qeuuuyhh', 'zzzklllhqnnwccchhh', 'zzzgjwwjj', 'ttldttt', 'ccciit', 'uddssxfaa', 'bblppttddrrgcc', 'ddjrrrs', 'bbtttnnqqqhspffeee', 'qqqwwwss', 'eennnsllxx', 'pppgggvvffv', 'llllllggvqq', 'jjffvvvennnrryyllhhh', 'qkhhhjjjpp', 'xjvvvyyyhhheiiipppiiibbb', 'nnjfffkkkooccc', 'vvsssppqqtttt', 'rrrsssddwwwmmmbmmm', 'ddzzjaaddd', 'kkkkbbsssnuepppywww', 'kkkjiiihhhittm', 'fffaar', 'wmmppuuuuuooouuu', 'rriaaacppfml', 'sssrrrjjjggssasxxh', 'dddfiihhh', 'qwwqgg', 'ssmd', 'qqqhhsss', 'uuyjxbeeeaan', 'aaakqqqvssqqqaaa', 'uunxxbbttt', 'wdfffnnnuuuuuuuu', 'ppeennaa', 'ddfgggzzgggdddyy', 'zukkkiwwwczzz', 'ffjjxxxbbpppoodddddd', 'eeenndddrrruuuqq', 'rrddhxxnnn', 'bbbjcccyyhs', 'bbaaoooo', 'ogvvveeecct', 'aaaibbhhhymm', 'ussb', 'ooopppttbbbcc', 'hhkkkaajjbs', 'hxpyyyee', 'ssskubbbf', 'ppppppooosnnhhoo', 'kqqwmzzzkkkyyy', 'mmueeeqqqqyyy', 'ppnnooo', 'xxccchhgggovnnn', 'hpeeeyyyiiigupp', 'kkooopppbbbbo', 'npwwwcccrrrerrroooaa', 'qqaaaibuufffyyaacqqq', 'ddmmmbbdeeesoojjjwwwc', 'iizzzssjxx', 'vvvvvnnkkbyyyf', 'zzzzzzbbbqqxxxlllhhhhhhtff', 'jjkkkhhhsoo', 'iiizzonndllleaaafff', 'wwwoffvvyzzzttqqq', 'bbarruuugggjgqf', 'kkkhhhqqe', 'gggatqqqeeetttteeooo', 'wwwza', 'vvvyyii', 'nnnqqlww', 'zhwvubzjjj', 'yhhvvvag', 'uuucymoogggq', 'kkkuuaooommmuuuvkfmmm', 'tttffybbaaabgggnnll', 'buuvvvaaaggguddrrggg', 'ddzzzzzz', 'bggglllmmtzzzooowwvv', 'sgrrsdyysu', 'ywllj', 'mnnmmqqqaa', 'cccrrrdzzddd', 'eellxxxvvvtmmmjjjcc', 'wwrrrlrxd', 'nxxjjjjjvccc', 'aaaooffd', 'reekkxxxuuuzhhyyyiee', 'ssllk', 'zzsssssstqqqqqwxxxwwnn', 'xxggrrrppxxnnliivvve', 'izzyyqgggqqqllxxxuu', 'ggaax', 'ssfffmmuu', 'aarvvrrryy'], 1));
  print(sol.longestConsec(["zone", "abigail", "theta", "form", "libe", "zas"], -2));
  //print(sol.longestConsec(['rrcccii', 'gggwpppccwccpppee', 'ylyyyrr', 'lloooooicccbbbpp', 'ffhooohhhoiiigggx', 'ddyyyvvvtfffkkyyybbke', 'wcccwwwd', 'vvbupppyiiyyyyjjj', 'yyiiilllkkgggpppzqqqo', 'viiicy', 'qrrryyvvvddd', 'sqqqhmmmrrrwwuuujjj', 'vvvuuunneqvvvddkkuuhhh', 'pppsrrr', 'biiizzz', 'wkktteecccssmmm', 'yyyxxbbbv', 'uttteeellooffzz', 'pvocccpssvv', 'rrrhhoottii', 'nnmmzzsss', 'ffnbqqfffrrroo', 'zzlddbbafffffaaa', 'ccrrvttggqbb', 'kdiitkkkhhh', 'exm', 'ccssuuyyynaeeekggq', 'bffmmm', 'pplcccpm', 'dddddjaaw', 'cccywwoojlleeeyqqq', 'jjaaahhhoo', 'jwwwwwxxbbipkffhhh', 'kkzzznccccdrrrht', 'yyyxghhhffsssss', 'kkkkkmmxxxrrrrr', 'yhhiidd', 'cccnwkkkeeed', 'fffmmozzfffssaiiixh', 'gggcyycccmmapdd', 'bbjjjcczz', 'aeeeggyytquukkgpp', 'kkwwrtk', 'jjjqlllzzbbb', 'ziittwwnnn', 'phkkkollliinnnllooo', 'fbppplllpppppphhq', 'pttpppgryyuuyy', 'uuuxmmmgwwwyyplll', 'ggjjjifoooyyze', 'qtttmlllryy', 'kkkqkkkvmrrxkk', 'jttmmnnccewwwmm', 'iyhjjjkkkpp', 'uuyyyooooccaarrqq', 'acuzzzp', 'vvvkkqbbbnntttazz', 'pjjjxxxb', 'rrruugbii', 'ooojjjuuuzjqqcjjgg', 'kkkuuunnnddd', 'rrreeetw', 'eppppcbbbqquuujj', 'fommmjjjwwjzwrmm', 'ktwwzzkuusfw', 'ezzntttczuuu', 'ggyytqqgg', 'lqqbaaqqqh', 'fwwnnndd', 'egkk', 'werrhhhzzzggguuugyyy', 'daaaehtttibbbhzbbb', 'vccjjqqbbqhvvpp', 'xxxfiiigggjjjwww', 'lldxxmmmzzzhjj', 'ntttnnn', 'iiwwwxxnnnttjj', 'eeeaageuujuuuvv', 'ssssssppooopppuusttjjj', 'hhsaaakkk', 'cccdddq', 'oodddpeeen', 'aaasbhhpzzzrr', 'qqqjjjqrrrjjqqqqqqo', 'jjjekkrrriiffcvv', 'ccceeejjwwwnnn', 'fvvvtttacrrzzrrr', 'uuuyydgggyyoyyywwkko', 'hhhyyjjjeooobbb', 'iibbwwotzzzhmmex', 'lllqbbghhhddb', 'qqqxxiigggn', 'vvvmmdlllddhhhqpprrruuu', 'xxxbbbccppeeuuuxdd', 'xxxaaaeeeyyyuuuggxjjtttnn', 'zsshhhs', 'twwuuhhhvv', 'mmmbbaeeflttt', 'bbwwwppee', 'vvzzzjwwwiixxxo', 'jjjjjjpgggxxdddddeee', 'gllltttwuuiiicvv', 'xxxewwlllyynnvvssqu', 'xpff', 'kuuuaaddd', 'xszzzruuu', 'wwwrbbvvhhetttmy', 'fnnntttsseettiionnnxx', 'wwrrtttwkkkzttteel', 'ttjjttt', 'obbbennnxxoommtt', 'ootttvvvppttwddvhhh', 'pppggmmnnrrrfffpppeeennvv', 'oootttaaaldddz', 'ozzmmfffbr', 'cffuccccccvvvuuui', 'jiiyygqq', 'nnnqruxxxunnnh', 'eegkknznbbbvv', 'vvvctsssjjjttaaavv', 'rpprsdddmmsp', 'qqeddeeesooaaoddr'], 108));
  //print(sol.longestConsec(['rrcccii', 'gggwpppccwccpppee', 'ylyyyrr', 'lloooooicccbbbpp', 'ffhooohhhoiiigggx', 'ddyyyvvvtfffkkyyybbke', 'wcccwwwd', 'vvbupppyiiyyyyjjj', 'yyiiilllkkgggpppzqqqo', 'viiicy', 'qrrryyvvvddd', 'sqqqhmmmrrrwwuuujjj', 'vvvuuunneqvvvddkkuuhhh', 'pppsrrr', 'biiizzz', 'wkktteecccssmmm', 'yyyxxbbbv', 'uttteeellooffzz', 'pvocccpssvv', 'rrrhhoottii', 'nnmmzzsss', 'ffnbqqfffrrroo', 'zzlddbbafffffaaa', 'ccrrvttggqbb', 'kdiitkkkhhh', 'exm', 'ccssuuyyynaeeekggq', 'bffmmm', 'pplcccpm', 'dddddjaaw', 'cccywwoojlleeeyqqq', 'jjaaahhhoo', 'jwwwwwxxbbipkffhhh', 'kkzzznccccdrrrht', 'yyyxghhhffsssss', 'kkkkkmmxxxrrrrr', 'yhhiidd', 'cccnwkkkeeed', 'fffmmozzfffssaiiixh', 'gggcyycccmmapdd', 'bbjjjcczz', 'aeeeggyytquukkgpp', 'kkwwrtk', 'jjjqlllzzbbb', 'ziittwwnnn', 'phkkkollliinnnllooo', 'fbppplllpppppphhq', 'pttpppgryyuuyy', 'uuuxmmmgwwwyyplll', 'ggjjjifoooyyze', 'qtttmlllryy', 'kkkqkkkvmrrxkk', 'jttmmnnccewwwmm', 'iyhjjjkkkpp', 'uuyyyooooccaarrqq', 'acuzzzp', 'vvvkkqbbbnntttazz', 'pjjjxxxb', 'rrruugbii', 'ooojjjuuuzjqqcjjgg', 'kkkuuunnnddd', 'rrreeetw', 'eppppcbbbqquuujj', 'fommmjjjwwjzwrmm', 'ktwwzzkuusfw', 'ezzntttczuuu', 'ggyytqqgg', 'lqqbaaqqqh', 'fwwnnndd', 'egkk', 'werrhhhzzzggguuugyyy', 'daaaehtttibbbhzbbb', 'vccjjqqbbqhvvpp', 'xxxfiiigggjjjwww', 'lldxxmmmzzzhjj', 'ntttnnn', 'iiwwwxxnnnttjj', 'eeeaageuujuuuvv', 'ssssssppooopppuusttjjj', 'hhsaaakkk', 'cccdddq', 'oodddpeeen', 'aaasbhhpzzzrr', 'qqqjjjqrrrjjqqqqqqo', 'jjjekkrrriiffcvv', 'ccceeejjwwwnnn', 'fvvvtttacrrzzrrr', 'uuuyydgggyyoyyywwkko', 'hhhyyjjjeooobbb', 'iibbwwotzzzhmmex', 'lllqbbghhhddb', 'qqqxxiigggn', 'vvvmmdlllddhhhqpprrruuu', 'xxxbbbccppeeuuuxdd', 'xxxaaaeeeyyyuuuggxjjtttnn', 'zsshhhs', 'twwuuhhhvv', 'mmmbbaeeflttt', 'bbwwwppee', 'vvzzzjwwwiixxxo', 'jjjjjjpgggxxdddddeee', 'gllltttwuuiiicvv', 'xxxewwlllyynnvvssqu', 'xpff', 'kuuuaaddd', 'xszzzruuu', 'wwwrbbvvhhetttmy', 'fnnntttsseettiionnnxx', 'wwrrtttwkkkzttteel', 'ttjjttt', 'obbbennnxxoommtt', 'ootttvvvppttwddvhhh', 'pppggmmnnrrrfffpppeeennvv', 'oootttaaaldddz', 'ozzmmfffbr', 'cffuccccccvvvuuui', 'jiiyygqq', 'nnnqruxxxunnnh', 'eegkknznbbbvv', 'vvvctsssjjjttaaavv', 'rpprsdddmmsp', 'qqeddeeesooaaoddr'], 108));
  print(sol.longestConsec(["tree", "foling", "trashy", "blue", "abcdef", "uvwxyz"], 2));
}

